### ISSUE TITLE
agendamento para encerrar consultas

### ISSUE THREAD

**Issue by yubathom** [SPURB/participe#13]
**Finalização de consulta**
Incluir funcionalidade de agendamento para encerrar consulta pelo admin. 

**Solução**
O admin deve ter o controle para agendar o encerramento de cada consulta por meio de um botão. 
Esta funcionalidade depende de alterações no backed [consultas-backend](https://github.com/SPURB/consultas-publicas-backend).

**Contexto de implementação no frontend**
Esta é uma funcionalidade que irá aparecer na área administrativa `/login` na área de **identificação**. 
 ![Localização do botão](https://screenshotscdn.firefoxusercontent.com/images/c661a399-2d4c-4810-b677-eb22c80aeacb.png)

**Comment by flavinhalopes** [comment]
Protótipo com função de encerramento da consulta: 
https://www.figma.com/file/Gl8bpkOzUupTg3aVGRVdkF/Cadastro-Consulta?node-id=291%3A40

**Comment by yubathom** [comment]
para encerrar
```
SET GLOBAL event_scheduler = ON;
CREATE EVENT encerra_nome_consulta
ON SCHEDULE AT TIMESTAMP("2018-12-12", "23:59:59")
DO
UPDATE `nomeDB`.`consultas` SET `ativo`='0' WHERE  `id_consulta`=00;
```

**Comment by yubathom** [comment]
resolvido em repositório privado do admin
