### ISSUE TITLE
Componente de Erro

### ISSUE THREAD

**Issue by educkf** [SPURB/participe#165]
**O problema**
Queria discutir a criação de um componente de erros.
A ideia surgiu quando estava preparando para escrever os testes unitários para o componente `src/components/Comments.vue`, e vi que a validação do form no mixin `commnetsCommons.js` retorna um `alert()` em caso de erro. Não acho essa maneira de todo absurda (um alert é universa, todo browser tem, e bloqueia o usuário até que ele veja a mensagem). Mas talvez consigamos uma opção mais interessante e amigável que possa ser reutilizado em outros lugares do projeto.

**Possível solução**
O @yubathom sugeriu que se criasse um componente de erro, que pudesse ser usado em outros lugares do projeto. Alguns requisitos que pensei:
- Permitir personalizar a frase de erro
- Permitir agrupar mais de um erro em lista (se no form faltar tanto email quanto nome, por exemplo)
- Possibilitar que seja tanto um .alert à moda [Bootstrap ](https://getbootstrap.com/docs/4.4/components/alerts/), quando uma modal que bloqueie a interação até que o erro seja lido (isso poderia ser feito por via de uma `prop` que passa nos atributos do componente de erro)

**Soluções alternativas**
Seria possível, por outro lado, criar também um component de Alert à moda Bootstrap, e que permita customização de cor para reportar se a mensagem é de erro, ou de sucesso.

Ainda não iniciei a construção do componente, queria apenas ver se existe alguma sugestão/pedido extra para ele :grin:

**Comment by yubathom** [comment]
@educkf, temos um protótipo, nada definido, mas que pode auxiliar na definição deste componente substituir estes alerts. Pensando bem este componente poderia ser usado em outros contextos, não restrito aos componentes de comentários.

Estou de acordo com os requisitos que você citou. 

![protótipo subcomponente comments](https://user-images.githubusercontent.com/4117768/72154312-168e8400-338f-11ea-8f24-83fc94ff1e0a.png)

![Sem-Título-2](https://user-images.githubusercontent.com/4117768/72155350-b51be480-3391-11ea-8d78-8611e6080088.png)

https://www.figma.com/proto/GHnnRldBUe5OmjYTMqcoLWhd/Participe?node-id=190%3A317&viewport=-545%2C273%2C0.1502244621515274&scaling=scale-down

**Comment by educkf** [comment]
Bacana!
Pelos exemplos, valeria que ele fosse não apenas pra erro, mas também pra sucesso ("Seu comentário foi enviado!") ?
O que muda seria apenas o nome do componente (ao invés de algo como `ErrorModal.vue` pra `AlertModal.vue`), e um prop extra pra designar se o alerta é de *sucesso*, *atenção* ou *erro*.

**Comment by yubathom** [comment]
Isso! 

Apesar do protótipo não acho que a mensagem de sucesso deva ser usada nos comentários. Usei a imagem apenas para ilustrar outros tipos de mensagens. 

Nos comentários temos uma mensagem de sucesso e erro que lida com as respostas da api no contexto da contribuição. 
![Sem-Título-7](https://user-images.githubusercontent.com/4117768/72156042-3aec5f80-3393-11ea-9fe0-f6cdfc482b64.png)

As três designações que você definiu me parecem bem certeiras também. Me parece genérico o suficiente para que este componente possa ser usado em outras situações. 

Não sei se você já viu mas documentamos um wiki com algumas definições de estilo:
https://github.com/SPURB/participe/wiki/Apresenta%C3%A7%C3%A3o

Este protótipo é bem antigo.. não precisa se restringir a ele..

**Comment by yubathom** [comment]
Fala @educkf, vamos tentar resolver isso por aqui. O @m-dantas irá desenvolver este componente.

**Comment by educkf** [comment]
Mandaver, @yubathom, desculpa não ter conseguido investir tempo no componente!

**Comment by yubathom** [comment]
Tranquillo @educkf!

**Comment by yubathom** [comment]
Resolvido em #187 e finalizado em [87bf093](https://github.com/SPURB/participe/commit/87bf09386baf5cd0163ae56875802d49fd69cc0b)

Obrigado @educkf e @m-dantas!

Falta fazer o teste unitário.
