### ISSUE TITLE
Tabelas - props csv

### ISSUE THREAD

**Issue by yubathom** [SPURB/participe#198]
**Sua funcionalidade se relaciona a um problema? Por favor descreva.**
A conversão de tabelas do word para a props do componente [Tabela](https://github.com/SPURB/participe/blob/master/src/components/Tabela.vue) é trabalhosa e poderia ser melhorada. 

**Descreva uma possível solução**
Alterar `Tabela.vue`  para que esta aceite uma notação diferente de props.

Nível da linha a atual notação é ` linha: [ { data: 'Conteúdo da célula' }],`. Se o modelo aceitar uma string no lugar do array de objetos simplificaria bastante as conversões.

**Descreva soluções alternativas**
Um novo componente como `TabelaCsv` que aceite csvs.

**Contexto adicional**
Notação atual
```javascript
linhas: [ // array de arrays com os conteúdos de cada linha (células)
    [ // primeira linha
        // cada célula de determinada linha é definida por um array que contém dois objetos:
        // 'data' é o conteúdo da célula em si e 'ref' é o conteúdo da nota de rodapé
        [ { data: 'Conteúdo da célula' }, { ref: 'Nota de rodapé da célula' } ],
        ...
    ],
],
```
Notação proposta
```javascript
linhas: [ // array de arrays com os conteúdos de cada linha (células)
    [  'Conteúdo da célula A1', 'Conteúdo da célula B1' ], // primeira linha 
    [  'Conteúdo da célula A2', 'Conteúdo da célula B2' ],  // segunda linha
    [  'Células A3-B3', 'Células A3-B3' ]  // terceira linha com colspan em strings idênticos
]

```
Poderia gerar 
<table>
  <tr>
    <td>Conteúdo da célula A1</td>
    <td>Conteúdo da célula B1</td>
  </tr>
  <tr>
    <td>Conteúdo da célula A2</td>
    <td>Conteúdo da célula B2</td>
  </tr>
  <tr>
    <td colspan="2">Células A3-B3</td>
  </tr>
</table>

Ver a atual [documentação do componente no wiki](https://github.com/SPURB/participe/wiki/Tabelas).

**Comment by m-dantas** [comment]
Componente criado, recebendo valores através de props.
**Passando valor das props:**
![Screenshot_10](https://user-images.githubusercontent.com/45770805/77699947-0cddeb00-6f92-11ea-9dce-3f9e39559725.png)
