### ISSUE TITLE
Comments.vue / Feedback comentários

### ISSUE THREAD

**Issue by flavinhalopes** [SPURB/participe#22]
**Falta de feedback nos comentários**
Não há um loader quando se comenta. Após enviar o comentário, o mesmo não desaparece do formulário e este não se fecha. 

**Ao comentar**
![screenshot_2018-11-14 participe gestao urbana 3](https://user-images.githubusercontent.com/39636035/48486642-45e54780-e803-11e8-8844-cfb078a2994a.png) 
![screenshot_2018-11-14 participe gestao urbana 2](https://user-images.githubusercontent.com/39636035/48486641-454cb100-e803-11e8-96cb-6e7c9fdb856c.png)
![screenshot_2018-11-14 participe gestao urbana](https://user-images.githubusercontent.com/39636035/48486643-45e54780-e803-11e8-8ff9-d9e1c5480c26.png) 
_O formulário permanece aberto e com o comentário realizado_.

**Possível solução**
Sugestão: incluir loader; confirmação ou reportar erro, seguido de fechamento da caixa de comentário.
A mensagem de confirmação na caixa de comentário (quando a caixa já estiver fechada, última imagem) ficará apenas por alguns segundos. Logo após, retornará a ficar disponível para novos comentários.
![esperado1](https://user-images.githubusercontent.com/39636035/48487196-a45ef580-e804-11e8-96ce-cee9ba8dcd82.png)
![esperado2](https://user-images.githubusercontent.com/39636035/48487197-a45ef580-e804-11e8-9162-16f9398d1952.png)
![esperado3](https://user-images.githubusercontent.com/39636035/48487198-a45ef580-e804-11e8-8279-067aef0914de.png)
![esperado4](https://user-images.githubusercontent.com/39636035/48487200-a4f78c00-e804-11e8-99ed-4c84c444453c.png)

**Comment by yubathom** [comment]
![action](https://user-images.githubusercontent.com/4117768/48489184-952e7680-e809-11e8-9fd7-4b59e91c3468.gif)
https://codepen.io/flavinhalopes/pen/KrNWdJ
animação do svg para colocar do botão durante o `fetch` do envio
