### ISSUE TITLE
Inputs de nome, sobrenome e email

### ISSUE THREAD

**Issue by nobruexe** [SPURB/participe#227]
**Descreva o problema**
Ao tentar realizar meus votos, não possuo **nenhum acesso** a link ou a input para preenchimento de informações.

**Capturas de tela**

![image](https://user-images.githubusercontent.com/49958155/88233728-78894980-cc4e-11ea-8b80-a2adf821f5b5.png)

**Informações do dispositivo:**
 - Dispositivo: [Dell Inspiron ]
 - Sistema operacional: [Windows 10]
 - Navegador [chrome]

**Comment by yubathom** [comment]
Olá @nobruexe , obrigado pelo relato. Acredito que o input não está disponível por que a consulta foi encerrada em maio. 

![Screenshot_2020-07-24 Participe Gestão Urbana](https://user-images.githubusercontent.com/4117768/88398276-8c8e9180-cd9b-11ea-933e-f92c9f995ffd.png)
> Ao encerrar a consulta o formulário com os inputs não são renderizados.

A redação do texto está confusa mesmo. Vou relatar o pessoal para que tomem cuidado com este tipo de ambiguidade.
