### ISSUE TITLE
Migrar banco-de-dados:

### ISSUE THREAD

**Issue by yubathom** [SPURB/participe#54]
## Descrição do problema
Os comentários devem ficar disponíveis em api.gestaourbana e se relacionar com as outras tabelas em um único bd. As consultas antigas estão no padrão wordpress com metatags. 

## Possível solução
Migrar os comentários para a tabela de comentários do atual banco do participe.

**Comment by yubathom** [comment]
- [ ] relacionar nome de banco com itens da tabela __consultas__ @lordscorp

**Comment by lordscorp** [comment]
Criada coluna (temporária) na tabela consultas chamada `db_antigo`, com os nomes dos bancos relacionados às consultas com wp próprio.

**Comment by yubathom** [comment]
Feito em homologação. Grande @hsolucas!
http://api.comunicacao.smul.pmsp/ ,   ver `consultas/` e `/members`. 

Iniciando desenvolvimento do frontend da documentação dos processos participativos do gestão urbana. Aguardando encerramento de todas as consultas para iniciar migração do __bd__ em produção.

**Comment by yubathom** [comment]
- [ ] frontend em homologação
- [ ] migração em produção

**Comment by yubathom** [comment]
@davimh pode iniciar o desenvolvimento frontend

**Comment by yubathom** [comment]
Feito. Documentação da API em ambiente de produção:
https://documenter.getpostman.com/view/4136141/S1ZxbpLD?version=latest
