### ISSUE TITLE
Encontro com movimentos de moradia (definição de priorização de backlog)

### ISSUE THREAD

**Issue by yubathom** [SPURB/participe#65]
#  Oficina de capacitação em consultas públicas on-line: PIU Arco Pinheiros / PIU Setor Central
Dia 22/05, quarta-feira, teremos esta oficina __ao vivo__ com integrantes de movimentos de moradia onde iremos apresentar os meios online de participação. 

Além de mostrar os sites e as funcionalidades pensei em criar um pequeno formulário de validação de alguns itens da nossa [lista de afazeres](https://github.com/orgs/SPURB/projects/1) para guiar o desenvolvimento. 

Desta forma, pensei em elencar cinco ou mais funcionalidades a serem desenvolvidas e criar um questionário onde o usuário irá elencar a prioridade dessa funcionalidade. Exemplificando:

> "O que faria você contribuir mais no nosso site? escolha uma opção:"
> Funcionalidade A: 
> [ ] não é importante  |  [ ] pouco importante  |  [ ] importante  |  [ ] muito importante
> 
> Funcionalidade B: 
> [ ] não é importante  |  [ ] pouco importante  |  [ ] importante  |  [ ] muito importante

Seria extremamete importane ilustrar o fluxo das funcionalidades. 

Também, para termos uma resposta criteriosa, considero restringir o número de funcionalidades para 5 itens. Nesta issue sugiro definir esta lista até sexta feira para termos tempo de ilustrar tudo.

Alguns critérios a serem considerados:
* Não elencar [axiomas](https://pt.wikipedia.org/wiki/Axioma). Exemplo de axioma neste contexto: "O app precisa carregar mais rápido" ou "As contribuições devem ser seguras".
* Ter como ponto de referência o usuário da aplicação, considerando o grupo deste evento.
* Não obrigatório, mas deve ser ilustrável. Para facilitar a apreensão da funcionalidade. 

Acho que aqui nesta issue cabe incluir detalhamento técnico de como seria implementado a funcionalidade. Porém não incluiremos isso no formulário.

**Comment by yubathom** [comment]
1. Incluir busca de endereço nos mapas. 
> Não no componente mapa mas nos mapas de cada projeto ex [centro](https://github.com/SPURB/mapa-consulta-setor-central) e [pinheiros](https://github.com/SPURB/mapa-consulta-arco-pinheiros)

**Comment by yubathom** [comment]
3. Receber notificações por email após conclusão e publicação de devolutivas

**Comment by yubathom** [comment]
4. Integração com whatsapp
> Pro futuro poderíamos estudar a [api deles](https://developers.facebook.com/docs/whatsapp/overview) e caprichar nesse tópico. Por hora pensei em algo bem mais simples. O whatsapp permite criar mensagens padronizadas pela concatenação de urls. Desta forma seria possível criar um fluxo de interação (whatsapp/participe) criando alguns padrões destas concatenações.

**Comment by davimh** [comment]
5. Incluir busca de consultas na home/Aprimorar a maneira do cidadão explorar as consultas da home
> As consultas poderiam ser categorizadas por assunto, território, órgão/entidade que a publicou, legislação correlata, etc. Essas categorias serviriam de parâmetro para a busca.

**Comment by yubathom** [comment]
6. Tópicos 
> Áreas comentáveis gerariam uma subrota com url específica na qual os comentários ficariam agrupados.

**Comment by davimh** [comment]
7. Áudio
> Permitir que o cidadão possa contribuir com áudios gravados no seu dispositivo.

**Comment by davimh** [comment]
8. Imagens
> Permitir que se anexe(m) imagem(ns) nas contribuições

**Comment by davimh** [comment]
9. Likes/dislikes
> Interações do tipo like/dislike nas contribuições, sendo que a mais curtida se sobrepõe (a ordem das contribuições é o número de likes menos o de dislikes)

**Comment by davimh** [comment]
10. Vídeo
> Exibir na consulta vídeo da equipe de projeto expondo o objeto da consulta (formato apresentação, entrevista).

**Comment by davimh** [comment]
11. Mapa interativo integrado na view da consulta
> Abrir a possibilidade de uma consulta poder ser lida com um mapa interativo na mesma página que, além de responder à comandos realizados na área do mapa, também responde aos eventos disparados no texto da consulta (passagem de um capítulo para outro, ativação/desativação de uma camada...)

**Comment by davimh** [comment]
12. Incluir devolutivas na própria view
> Depois de encerrado o período de contribuições, incluir como respostas suas respectivas devolutivas, logo abaixo delas, referenciando-as

**Comment by yubathom** [comment]
> 
> 
>     1. Incluir busca de endereço nos mapas.
> 
> 
> > Não no componente mapa mas nos mapas de cada projeto ex [centro](https://github.com/SPURB/mapa-consulta-setor-central) e [pinheiros](https://github.com/SPURB/mapa-consulta-arco-pinheiros)

1
protótipo e telas
https://www.figma.com/proto/T2ZwJqm1gIFHdm7QxNgwFvj6/github.com-spurb-participe-issues-65?node-id=2%3A129&viewport=648%2C462%2C0.338676780462265&scaling=min-zoom

Padronizar próximas telas para celulares de 375x667

**Comment by yubathom** [comment]
> 
> 
>     2. Georeferenciar contribuições associando contribuições à coordenadas

2
protótipo / telas
https://www.figma.com/proto/T2ZwJqm1gIFHdm7QxNgwFvj6/github.com-spurb-participe-issues-65?node-id=13%3A17&viewport=711%2C29%2C0.22679418325424194&scaling=min-zoom

**Comment by yubathom** [comment]
>     3. Receber notificações por email após conclusão e publicação de devolutivas
https://www.figma.com/proto/T2ZwJqm1gIFHdm7QxNgwFvj6/github.com-spurb-participe-issues-65?node-id=22%3A4&viewport=779%2C-594%2C0.3125753402709961&scaling=min-zoom

3
protótipo / telas

**Comment by yubathom** [comment]
> 
> 
>     7. Áudio
> 
> 
> > Permitir que o cidadão possa contribuir com áudios gravados no seu dispositivo.

7.

Simulação uso
https://drive.google.com/file/d/1ybVCNyqZ-M5-7mxxpXoeW_2yuzCN6fI3/view?usp=sharing

 Tela
https://www.figma.com/proto/T2ZwJqm1gIFHdm7QxNgwFvj6/github.com-spurb-participe-issues-65?node-id=36%3A0&viewport=769%2C496%2C0.48899516463279724&scaling=scale-down

**Comment by yubathom** [comment]
>     8. Imagens
> > Permitir que se anexe(m) imagem(ns) nas contribuições

8.
Simulação
[https://drive.google.com/file/d/1alCDr0C6jhnsTgBswTUhZU3LNQFn9onf/view?usp=sharing](https://drive.google.com/file/d/1alCDr0C6jhnsTgBswTUhZU3LNQFn9onf/view?usp=sharing)

Tela
https://www.figma.com/proto/T2ZwJqm1gIFHdm7QxNgwFvj6/github.com-spurb-participe-issues-65?node-id=50%3A69&viewport=440%2C493%2C0.7861544489860535&scaling=scale-down

**Comment by davimh** [comment]
> 
> 
>     6. Tópicos
> 
> 
> > Áreas comentáveis gerariam uma subrota com url específica na qual os comentários ficariam agrupados.

6.
Protótipo/telas
[https://www.figma.com/proto/T2ZwJqm1gIFHdm7QxNgwFvj6/github.com-spurb-participe-issues-65?node-id=49%3A237&viewport=444%2C307%2C0.6900935769081116&scaling=min-zoom](https://www.figma.com/proto/T2ZwJqm1gIFHdm7QxNgwFvj6/github.com-spurb-participe-issues-65?node-id=49%3A237&viewport=444%2C307%2C0.6900935769081116&scaling=min-zoom)

**Comment by davimh** [comment]
> 
> 
>     8. Likes/dislikes
> 
> 
> > Interações do tipo like/dislike nas contribuições, sendo que a mais curtida se sobrepõe (a ordem das contribuições é o número de likes menos o de dislikes)

8.
Protótipo/telas
https://www.figma.com/proto/T2ZwJqm1gIFHdm7QxNgwFvj6/github.com-spurb-participe-issues-65?node-id=49%3A313&viewport=487%2C243%2C0.578855574131012&scaling=min-zoom(https://www.figma.com/proto/T2ZwJqm1gIFHdm7QxNgwFvj6/github.com-spurb-participe-issues-65?node-id=49%3A313&viewport=487%2C243%2C0.578855574131012&scaling=min-zoom)

**Comment by davimh** [comment]
> 
> 
>     10. Vídeo
> 
> 
> > Exibir na consulta vídeo da equipe de projeto expondo o objeto da consulta (formato apresentação, entrevista).

10.
Protótipo/telas
https://www.figma.com/proto/T2ZwJqm1gIFHdm7QxNgwFvj6/github.com-spurb-participe-issues-65?node-id=49%3A379&viewport=509%2C159%2C0.9606930613517761&scaling=min-zoom(https://www.figma.com/proto/T2ZwJqm1gIFHdm7QxNgwFvj6/github.com-spurb-participe-issues-65?node-id=49%3A379&viewport=509%2C159%2C0.9606930613517761&scaling=min-zoom)

**Comment by davimh** [comment]
> 
> 
>     12. Incluir devolutivas na própria view
> 
> 
> > Depois de encerrado o período de contribuições, incluir como respostas suas respectivas devolutivas, logo abaixo delas, referenciando-as

12.
Protótipo/telas
https://www.figma.com/proto/T2ZwJqm1gIFHdm7QxNgwFvj6/github.com-spurb-participe-issues-65?node-id=49%3A363&viewport=699%2C124%2C0.6970465779304504&scaling=min-zoom(https://www.figma.com/proto/T2ZwJqm1gIFHdm7QxNgwFvj6/github.com-spurb-participe-issues-65?node-id=49%3A363&viewport=699%2C124%2C0.6970465779304504&scaling=min-zoom)

**Comment by yubathom** [comment]
Questionário completo:

https://drive.google.com/file/d/1cIeQwk1KxMrRxXX1-U0j0WLI1NSF68CB/view?usp=sharing

**Comment by davimh** [comment]
# Apresentação
https://docs.google.com/presentation/d/1aR_2NtSDU5hT8Qh3axWpNgamIWDcC6t6u6D28fmmg-E/edit?usp=sharing(https://docs.google.com/presentation/d/1aR_2NtSDU5hT8Qh3axWpNgamIWDcC6t6u6D28fmmg-E/edit?usp=sharing)

**Comment by yubathom** [comment]
Formulários preenchidos:
https://drive.google.com/open?id=1lVPd65H31WaJZeXD9tn5XhXHh3leeA5t
